/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.gymcontroller.pantallas;

import com.mycompany.gymcontroller.controllers.EjercicioController;
import com.mycompany.gymcontroller.modelo.Ejercicio;
import java.awt.Component;
import java.util.List;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;




public class PanelRutina extends javax.swing.JPanel {

    // Referencia al controlador de ejercicios
    private EjercicioController ejercicioController;

    public PanelRutina(EjercicioController ejercicioController) {
        initComponents();
         ejercicioController = new EjercicioController();
    }

    PanelRutina() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void cargarEjercicios() {
    // Limpia el panel para evitar duplicados
    panelCheckBoxes.removeAll();

    // Obtiene la lista de ejercicios desde el controlador
    List<Ejercicio> ejercicios = ejercicioController.obtenerEjercicios();
    for (Ejercicio ejercicio : ejercicios) {
        JCheckBox checkBox = new JCheckBox(ejercicio.getNombre() + " (" + ejercicio.getCategoria() + ")");
        panelCheckBoxes.add(checkBox); // Añade el checkbox al panel
    }

    // Refresca el panel para mostrar los nuevos componentes
    panelCheckBoxes.revalidate();
    panelCheckBoxes.repaint();
}
    
    private void procesarSeleccionados() {
    StringBuilder seleccionados = new StringBuilder("Ejercicios seleccionados:\n");

    for (Component comp : panelCheckBoxes.getComponents()) {
        if (comp instanceof JCheckBox) {
            JCheckBox checkBox = (JCheckBox) comp;
            if (checkBox.isSelected()) {
                seleccionados.append(checkBox.getText()).append("\n");
            }
        }
    }

    JOptionPane.showMessageDialog(this, seleccionados.toString());
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelRutina = new javax.swing.JPanel();
        btnCargarEjercicios = new javax.swing.JButton();
        btnProcesarSeleccionados = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelCheckBoxes = new javax.swing.JPanel();

        btnCargarEjercicios.setText("Cargar Ejercicios");
        btnCargarEjercicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarEjerciciosActionPerformed(evt);
            }
        });

        btnProcesarSeleccionados.setText("Procesar Seleccionados");
        btnProcesarSeleccionados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcesarSeleccionadosActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Lista Ejercicios");

        panelCheckBoxes.setLayout(new javax.swing.BoxLayout(panelCheckBoxes, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(panelCheckBoxes);

        javax.swing.GroupLayout PanelRutinaLayout = new javax.swing.GroupLayout(PanelRutina);
        PanelRutina.setLayout(PanelRutinaLayout);
        PanelRutinaLayout.setHorizontalGroup(
            PanelRutinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRutinaLayout.createSequentialGroup()
                .addGroup(PanelRutinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelRutinaLayout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel1))
                    .addGroup(PanelRutinaLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(PanelRutinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelRutinaLayout.createSequentialGroup()
                                .addComponent(btnCargarEjercicios)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnProcesarSeleccionados)))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        PanelRutinaLayout.setVerticalGroup(
            PanelRutinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRutinaLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelRutinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCargarEjercicios)
                    .addComponent(btnProcesarSeleccionados))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelRutina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelRutina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCargarEjerciciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarEjerciciosActionPerformed

         cargarEjercicios();
        
    }//GEN-LAST:event_btnCargarEjerciciosActionPerformed

    private void btnProcesarSeleccionadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcesarSeleccionadosActionPerformed

        procesarSeleccionados();
        
    }//GEN-LAST:event_btnProcesarSeleccionadosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelRutina;
    private javax.swing.JButton btnCargarEjercicios;
    private javax.swing.JButton btnProcesarSeleccionados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelCheckBoxes;
    // End of variables declaration//GEN-END:variables
}
