/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.gymcontroller.pantallas;

import java.awt.BorderLayout;

/**
 *
 * @author William Arias
 */
public class PanelEjercicios extends javax.swing.JPanel {

    /**
     * Creates new form PanelEjercicios
     */
    public PanelEjercicios() {
        initComponents();
        
        Ejercicios1 p1 = new Ejercicios1();
        p1.setSize(247, 199);
        p1.setLocation(0, 0);
        
        contenido.removeAll();
        contenido.add(p1, BorderLayout.CENTER);
        contenido.revalidate();
        contenido.repaint();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        contenido = new javax.swing.JPanel();
        ejercicioBtn1 = new javax.swing.JButton();
        ejercicioBtn2 = new javax.swing.JButton();
        ejercicioBtn3 = new javax.swing.JButton();
        ejercicioBtn4 = new javax.swing.JButton();
        ejercicioBtn5 = new javax.swing.JButton();

        jLabel1.setText("Tipos Ejercicios");

        jLabel2.setText("Lista");

        javax.swing.GroupLayout contenidoLayout = new javax.swing.GroupLayout(contenido);
        contenido.setLayout(contenidoLayout);
        contenidoLayout.setHorizontalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 199, Short.MAX_VALUE)
        );
        contenidoLayout.setVerticalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 247, Short.MAX_VALUE)
        );

        ejercicioBtn1.setText("Fuerza");
        ejercicioBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejercicioBtn1ActionPerformed(evt);
            }
        });

        ejercicioBtn2.setText("Cardio");
        ejercicioBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejercicioBtn2ActionPerformed(evt);
            }
        });

        ejercicioBtn3.setText("Flexibilidad");
        ejercicioBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejercicioBtn3ActionPerformed(evt);
            }
        });

        ejercicioBtn4.setText("Equilibrio");
        ejercicioBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejercicioBtn4ActionPerformed(evt);
            }
        });

        ejercicioBtn5.setText("Resistencia");
        ejercicioBtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejercicioBtn5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ejercicioBtn1)
                    .addComponent(ejercicioBtn2)
                    .addComponent(ejercicioBtn3)
                    .addComponent(ejercicioBtn4)
                    .addComponent(ejercicioBtn5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(contenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(139, 139, 139))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ejercicioBtn1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ejercicioBtn2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ejercicioBtn3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ejercicioBtn4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ejercicioBtn5)))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ejercicioBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejercicioBtn1ActionPerformed
        Ejercicios1 p1 = new Ejercicios1();
        p1.setSize(247, 199);
        p1.setLocation(0, 0);
        
        contenido.removeAll();
        contenido.add(p1, BorderLayout.CENTER);
        contenido.revalidate();
        contenido.repaint();
    }//GEN-LAST:event_ejercicioBtn1ActionPerformed

    private void ejercicioBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejercicioBtn2ActionPerformed
        Ejercicios2 p2 = new Ejercicios2();
        p2.setSize(247, 199);
        p2.setLocation(0, 0);
        
        contenido.removeAll();
        contenido.add(p2, BorderLayout.CENTER);
        contenido.revalidate();
        contenido.repaint();
    }//GEN-LAST:event_ejercicioBtn2ActionPerformed

    private void ejercicioBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejercicioBtn3ActionPerformed
        Ejercicios3 p3 = new Ejercicios3();
        p3.setSize(247, 199);
        p3.setLocation(0, 0);
        
        contenido.removeAll();
        contenido.add(p3, BorderLayout.CENTER);
        contenido.revalidate();
        contenido.repaint();
    }//GEN-LAST:event_ejercicioBtn3ActionPerformed

    private void ejercicioBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejercicioBtn4ActionPerformed
        Ejercicios4 p4 = new Ejercicios4();
        p4.setSize(247, 199);
        p4.setLocation(0, 0);
        
        contenido.removeAll();
        contenido.add(p4, BorderLayout.CENTER);
        contenido.revalidate();
        contenido.repaint();
    }//GEN-LAST:event_ejercicioBtn4ActionPerformed

    private void ejercicioBtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejercicioBtn5ActionPerformed
        Ejercicios5 p5 = new Ejercicios5();
        p5.setSize(247, 199);
        p5.setLocation(0, 0);
        
        contenido.removeAll();
        contenido.add(p5, BorderLayout.CENTER);
        contenido.revalidate();
        contenido.repaint();
    }//GEN-LAST:event_ejercicioBtn5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contenido;
    private javax.swing.JButton ejercicioBtn1;
    private javax.swing.JButton ejercicioBtn2;
    private javax.swing.JButton ejercicioBtn3;
    private javax.swing.JButton ejercicioBtn4;
    private javax.swing.JButton ejercicioBtn5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
