/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gymcontroller.pantallas;

import com.mycompany.gymcontroller.controllers.UsuarioController;
import com.mycompany.gymcontroller.modelo.Rutina;

/**
 *
 * @author Dorothea Ramirez
 */
public class Principal extends javax.swing.JFrame {
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mPrincipal = new javax.swing.JMenu();
        jmCrearMantenimiento = new javax.swing.JMenuItem();
        jmCrearUsuario = new javax.swing.JMenuItem();
        jmEjercicios = new javax.swing.JMenuItem();
        jmListaEjercicio = new javax.swing.JMenuItem();
        jmMostrarEjercicios = new javax.swing.JMenuItem();
        jmAgregarRutina = new javax.swing.JMenuItem();
        jmUsuariosC = new javax.swing.JMenuItem();
        jmMembresia = new javax.swing.JCheckBoxMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mPrincipal.setText("Mantenimiento");

        jmCrearMantenimiento.setText("Crear mantenimiento");
        jmCrearMantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCrearMantenimientoActionPerformed(evt);
            }
        });
        mPrincipal.add(jmCrearMantenimiento);

        jmCrearUsuario.setText("Crear usuario");
        jmCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCrearUsuarioActionPerformed(evt);
            }
        });
        mPrincipal.add(jmCrearUsuario);

        jmEjercicios.setText("Ejercicios");
        jmEjercicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmEjerciciosActionPerformed(evt);
            }
        });
        mPrincipal.add(jmEjercicios);

        jmListaEjercicio.setText("Lista Ejercicio");
        jmListaEjercicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmListaEjercicioActionPerformed(evt);
            }
        });
        mPrincipal.add(jmListaEjercicio);

        jmMostrarEjercicios.setText("Mostrar Ejercicios");
        jmMostrarEjercicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmMostrarEjerciciosActionPerformed(evt);
            }
        });
        mPrincipal.add(jmMostrarEjercicios);

        jmAgregarRutina.setText("Agregar Rutina");
        jmAgregarRutina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAgregarRutinaActionPerformed(evt);
            }
        });
        mPrincipal.add(jmAgregarRutina);

        jmUsuariosC.setText("Usuarios");
        jmUsuariosC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmUsuariosCActionPerformed(evt);
            }
        });
        mPrincipal.add(jmUsuariosC);

        jmMembresia.setSelected(true);
        jmMembresia.setText("Membresia");
        jmMembresia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmMembresiaActionPerformed(evt);
            }
        });
        mPrincipal.add(jmMembresia);

        jMenuBar1.add(mPrincipal);
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCrearUsuarioActionPerformed
        // TODO add your handling code here:
//        RegistroUsuario crearUsuario = new RegistroUsuario();
//        this.setContentPane(crearUsuario);
//        crearUsuario.setVisible(true);
        RegistroUsuario registroUsuario = new RegistroUsuario();
        registroUsuario.setVisible(true);
    }//GEN-LAST:event_jmCrearUsuarioActionPerformed

    private void jmUsuariosCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmUsuariosCActionPerformed
        // TODO add your handling code here:
         ListaUsuarios  pUsuarios = new ListaUsuarios();
         this.setContentPane(pUsuarios);    
         pUsuarios.setVisible(true);
    }//GEN-LAST:event_jmUsuariosCActionPerformed

    private void jmListaEjercicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmListaEjercicioActionPerformed
        // TODO add your handling code here:
        ListaEjercicios jmListaEjercicio = new ListaEjercicios();
        jmListaEjercicio.setVisible(true);
        this.setContentPane(jmListaEjercicio);
    }//GEN-LAST:event_jmListaEjercicioActionPerformed

    private void jmMembresiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmMembresiaActionPerformed
        // TODO add your handling code here:
        PanelMembresia jmMembresia = new PanelMembresia();
        this.setContentPane(jmMembresia);
        jmMembresia.setVisible(true);
    }//GEN-LAST:event_jmMembresiaActionPerformed

    private void jmEjerciciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmEjerciciosActionPerformed
        // TODO add your handling code here:
        Ejercicios jmEjercicios = new Ejercicios();
        this.setContentPane(jmEjercicios);
        jmEjercicios.setVisible(true);
    }//GEN-LAST:event_jmEjerciciosActionPerformed

    private void jmMostrarEjerciciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmMostrarEjerciciosActionPerformed
        // TODO add your handling code here:
         PanelRutina jmMostrarEjercicios = new PanelRutina();
        this.setContentPane(jmMostrarEjercicios);
        jmMostrarEjercicios.setVisible(true);
    }//GEN-LAST:event_jmMostrarEjerciciosActionPerformed

    private void jmAgregarRutinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAgregarRutinaActionPerformed
        // TODO add your handling code here:
         SeleccionarRutinas jmAgregarRutina = new SeleccionarRutinas();
         this.setContentPane(jmAgregarRutina);
         jmAgregarRutina.setVisible(true);
    }//GEN-LAST:event_jmAgregarRutinaActionPerformed

    private void jmCrearMantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCrearMantenimientoActionPerformed
        // TODO add your handling code here:
        ListaEjercicios crearMantenimiento = new ListaEjercicios();
        this.setContentPane(crearMantenimiento);
        crearMantenimiento.setVisible(true);
    }//GEN-LAST:event_jmCrearMantenimientoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem jmAgregarRutina;
    private javax.swing.JMenuItem jmCrearMantenimiento;
    private javax.swing.JMenuItem jmCrearUsuario;
    private javax.swing.JMenuItem jmEjercicios;
    private javax.swing.JMenuItem jmListaEjercicio;
    private javax.swing.JCheckBoxMenuItem jmMembresia;
    private javax.swing.JMenuItem jmMostrarEjercicios;
    private javax.swing.JMenuItem jmUsuariosC;
    private javax.swing.JMenu mPrincipal;
    // End of variables declaration//GEN-END:variables

    private void setContentPaEjerciciosne(Ejercicios jmEjercicios) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
