/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gymcontroller.pantallas;

import com.mycompany.gymcontroller.controllers.UsuarioController;
import com.mycompany.gymcontroller.modelo.Rutina;

/**
 *
 * @author Dorothea Ramirez
 */
public class Principal extends javax.swing.JFrame {
    
     UsuarioController u = new UsuarioController();

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        cargarDatos("");
        this.setLocationRelativeTo(null);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmCrearMantenimiento = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jmEjercicios = new javax.swing.JMenuItem();
        jmListaEjercicio = new javax.swing.JMenuItem();
        jmMostrarEjercicios = new javax.swing.JMenuItem();
        jmAgregarRutina = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jMenu1.setText("Mantenimiento");

        jmCrearMantenimiento.setText("Crear mantenimiejnto");
        jmCrearMantenimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jmCrearMantenimientoMousePressed(evt);
            }
        });
        jMenu1.add(jmCrearMantenimiento);

        jMenuItem2.setText("Crear usuario");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jmEjercicios.setText("Ejercicios");
        jmEjercicios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jmEjerciciosMousePressed(evt);
            }
        });
        jMenu1.add(jmEjercicios);

        jmListaEjercicio.setText("Lista Ejercicio");
        jmListaEjercicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jmListaEjercicioMousePressed(evt);
            }
        });
        jMenu1.add(jmListaEjercicio);

        jmMostrarEjercicios.setText("Mostrar Ejercicios");
        jmMostrarEjercicios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jmMostrarEjerciciosMousePressed(evt);
            }
        });
        jMenu1.add(jmMostrarEjercicios);

        jmAgregarRutina.setText("Agregar Rutina");
        jmAgregarRutina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jmAgregarRutinaMousePressed(evt);
            }
        });
        jMenu1.add(jmAgregarRutina);

        jMenuItem1.setText("Usuarios");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmCrearMantenimientoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmCrearMantenimientoMousePressed
        // TODO add your handling code here:
     
        ListaEjercicios crearMantenimiento = new ListaEjercicios();
        this.setContentPane(crearMantenimiento);
        crearMantenimiento.setVisible(true);
        
    }//GEN-LAST:event_jmCrearMantenimientoMousePressed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jmAgregarRutinaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmAgregarRutinaMousePressed
        
        SeleccionarRutinas jmAgregarRutina = new SeleccionarRutinas();
        this.setContentPane(jmAgregarRutina);
        jmAgregarRutina.setVisible(true);
        
    }//GEN-LAST:event_jmAgregarRutinaMousePressed

    private void jmMostrarEjerciciosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmMostrarEjerciciosMousePressed
        
        PanelRutina jmMostrarEjercicios = new PanelRutina();
        this.setContentPane(jmMostrarEjercicios);
        jmMostrarEjercicios.setVisible(true);
        
    }//GEN-LAST:event_jmMostrarEjerciciosMousePressed

    private void jmEjerciciosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmEjerciciosMousePressed
        
        Ejercicios jmEjercicios = new Ejercicios();
        this.setContentPane(jmEjercicios);
        jmEjercicios.setVisible(true);
        
        
    }//GEN-LAST:event_jmEjerciciosMousePressed

    private void jmListaEjercicioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmListaEjercicioMousePressed
        
        ListaEjercicios jmListaEjercicio = new ListaEjercicios();
        this.setContentPane(jmListaEjercicio);
        jmListaEjercicio.setVisible(true);
        
    }//GEN-LAST:event_jmListaEjercicioMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem jmAgregarRutina;
    private javax.swing.JMenuItem jmCrearMantenimiento;
    private javax.swing.JMenuItem jmEjercicios;
    private javax.swing.JMenuItem jmListaEjercicio;
    private javax.swing.JMenuItem jmMostrarEjercicios;
    // End of variables declaration//GEN-END:variables

    private void setContentPaEjerciciosne(Ejercicios jmEjercicios) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
