/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.gymcontroller.pantallas;

import com.mycompany.gymcontroller.controllers.UsuarioController;
import com.mycompany.gymcontroller.modelo.Ejercicio;
import com.mycompany.gymcontroller.modelo.Rutina;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;

/**
 *
 * @author William Arias
 */
public class SeleccionarRutinas extends javax.swing.JPanel {
    
     // Declaración de variables
    
    

    /**
     * Creates new form SeleccionarRutinas
     */
    public SeleccionarRutinas() {
        initComponents();
    }
    
    // Método para cargar rutinas
    void cargarRutinas(List<Ejercicio> ejerciciosSeleccionados) {
        // Crear una lista de nombres de ejercicios a partir de los objetos Ejercicio
        List<String> nombresEjercicios = ejerciciosSeleccionados.stream()
                                                               .map(Ejercicio::getNombre)
                                                               .collect(Collectors.toList());

        // Actualizar el JList con los nombres de los ejercicios seleccionados
        listaEjerciciosSeleccionados.setListData(nombresEjercicios.toArray(new String[0]));
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listaEjerciciosSeleccionados = new javax.swing.JList<>();
        btnAsignarRutinas = new javax.swing.JButton();
        btnLimpiarSeleccion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));

        listaEjerciciosSeleccionados.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listaEjerciciosSeleccionados);

        btnAsignarRutinas.setBackground(new java.awt.Color(255, 255, 102));
        btnAsignarRutinas.setText("Asignar Rutinas");
        btnAsignarRutinas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAsignarRutinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarRutinasActionPerformed(evt);
            }
        });

        btnLimpiarSeleccion.setBackground(new java.awt.Color(255, 102, 0));
        btnLimpiarSeleccion.setText("Limpiar Seleccion");
        btnLimpiarSeleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarSeleccionActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ejercicios Seleccionados");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnAsignarRutinas, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLimpiarSeleccion)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addContainerGap(314, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAsignarRutinas, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLimpiarSeleccion)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAsignarRutinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarRutinasActionPerformed
        // Obtener los ejercicios seleccionados de la lista
    List<String> ejerciciosAsignados = listaEjerciciosSeleccionados.getSelectedValuesList();

    if (ejerciciosAsignados.isEmpty()) {
        System.out.println("No hay ejercicios seleccionados para asignar.");
    } else {
        String usuarioNombre = "nombreDelUsuario";  // Aquí deberías obtener el nombre de usuario de forma dinámica

        // Asignar cada ejercicio seleccionado al usuario
        UsuarioController usuarioController = new UsuarioController();
        for (String nombreEjercicio : ejerciciosAsignados) {
            Rutina rutina = new Rutina(nombreEjercicio);  // Crear una rutina para el ejercicio seleccionado
            usuarioController.asignarRutinaAUsuario(usuarioNombre, rutina);
            System.out.println("Ejercicio asignado al usuario: " + nombreEjercicio);
        }
        System.out.println("Rutinas asignadas al usuario: " + usuarioNombre);
    }
    
    if (ejerciciosAsignados.isEmpty()) {
        System.out.println("No hay ejercicios seleccionados para asignar.");
    } else {
        String usuarioNombre = "nombreDelUsuario";  // Obtén el nombre del usuario de manera dinámica

        UsuarioController usuarioController = new UsuarioController();
        for (String nombreEjercicio : ejerciciosAsignados) {
            Rutina rutina = new Rutina(nombreEjercicio);
            usuarioController.asignarRutinaAUsuario(usuarioNombre, rutina);
            System.out.println("Ejercicio asignado al usuario: " + nombreEjercicio);
        }

        // Mostrar mensaje de éxito
        JOptionPane.showMessageDialog(this, "Rutinas asignadas correctamente al usuario " + usuarioNombre, "Éxito", JOptionPane.INFORMATION_MESSAGE);
    }
    }//GEN-LAST:event_btnAsignarRutinasActionPerformed

    private void btnLimpiarSeleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarSeleccionActionPerformed
        listaEjerciciosSeleccionados.clearSelection();  // Limpiar la selección de la lista
    }//GEN-LAST:event_btnLimpiarSeleccionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignarRutinas;
    private javax.swing.JButton btnLimpiarSeleccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listaEjerciciosSeleccionados;
    // End of variables declaration//GEN-END:variables
}
